### ISSUE TITLE
After post processing the results are slightly improved

### ISSUE THREAD

**Issue by nitinmukesh** [rlgnswk/NeRFFaceSpeech_Code#5]
https://github.com/user-attachments/assets/a480f936-a376-4cf3-92b2-5c97e45c9fab

Left is the output from tool, and right is after gfpgan.

The pipeline can be included in the tool easily and code is available in the following repos.
https://github.com/X-LANCE/AniTalker
https://github.com/tanshuai0219/EDTalk

**Comment by rlgnswk** [comment]
Thank you for deriving additional results!

I recognize that existing research suggests that post-processing can enhance the final quality. However, since this is not the method proposed in this paper, I believe it should not be included.

Nonetheless, I really appreciate that you demonstrated this through experiments. 

If it’s alright, I would like to mention this issue in the Readme to inform others about this method.

**Comment by nitinmukesh** [comment]
Yes, please you can mention in Readme.

I will do more test with inference methods tomorrow.

**Comment by rlgnswk** [comment]
I've updated it! Thank you for making the code more complete.
